# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 530, 300))
        self.frame.setStyleSheet("background:url(:/img/resources/bg.jpg)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedPage = QtWidgets.QStackedWidget(self.frame)
        self.stackedPage.setGeometry(QtCore.QRect(60, 30, 381, 241))
        self.stackedPage.setStyleSheet("background:transparent")
        self.stackedPage.setObjectName("stackedPage")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.frame_5 = QtWidgets.QFrame(self.page_15)
        self.frame_5.setGeometry(QtCore.QRect(190, 106, 181, 125))
        self.frame_5.setStyleSheet("background:rgba(5,5,15,100);\n"
"border-radius : 5px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.weatherVal = QtWidgets.QLabel(self.frame_5)
        self.weatherVal.setGeometry(QtCore.QRect(105, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(15)
        self.weatherVal.setFont(font)
        self.weatherVal.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.weatherVal.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherVal.setObjectName("weatherVal")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 3, 91, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.label_18.setObjectName("label_18")
        self.stackedWeather = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWeather.setGeometry(QtCore.QRect(15, 40, 71, 81))
        self.stackedWeather.setStyleSheet("background:transparent;")
        self.stackedWeather.setObjectName("stackedWeather")
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.graphicsView_14 = QtWidgets.QGraphicsView(self.page_16)
        self.graphicsView_14.setGeometry(QtCore.QRect(0, 0, 63, 67))
        self.graphicsView_14.setStyleSheet("background:url(:/img/resources/weather/day.png);\n"
"border:transparent;\n"
"")
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.stackedWeather.addWidget(self.page_16)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.graphicsView_15 = QtWidgets.QGraphicsView(self.page_17)
        self.graphicsView_15.setGeometry(QtCore.QRect(5, 5, 63, 56))
        self.graphicsView_15.setStyleSheet("background:url(:/img/resources/weather/night.png);\n"
"border:transparent")
        self.graphicsView_15.setObjectName("graphicsView_15")
        self.stackedWeather.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.graphicsView_16 = QtWidgets.QGraphicsView(self.page_18)
        self.graphicsView_16.setGeometry(QtCore.QRect(0, 10, 63, 47))
        self.graphicsView_16.setStyleSheet("background:url(:/img/resources/weather/cloudy.png);\n"
"border:transparent")
        self.graphicsView_16.setObjectName("graphicsView_16")
        self.stackedWeather.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.graphicsView_17 = QtWidgets.QGraphicsView(self.page_19)
        self.graphicsView_17.setGeometry(QtCore.QRect(0, 10, 63, 39))
        self.graphicsView_17.setStyleSheet("background:url(:/img/resources/weather/more_cloudy.png);\n"
"border:transparent")
        self.graphicsView_17.setObjectName("graphicsView_17")
        self.stackedWeather.addWidget(self.page_19)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.graphicsView_23 = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView_23.setGeometry(QtCore.QRect(0, 7, 63, 55))
        self.graphicsView_23.setStyleSheet("background:url(:/img/resources/weather/haze.png);\n"
"border:transparent")
        self.graphicsView_23.setObjectName("graphicsView_23")
        self.stackedWeather.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.graphicsView_24 = QtWidgets.QGraphicsView(self.page_6)
        self.graphicsView_24.setGeometry(QtCore.QRect(0, 0, 63, 67))
        self.graphicsView_24.setStyleSheet("background:url(:/img/resources/weather/rainy.png);\n"
"border:transparent")
        self.graphicsView_24.setObjectName("graphicsView_24")
        self.stackedWeather.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.graphicsView_25 = QtWidgets.QGraphicsView(self.page_7)
        self.graphicsView_25.setGeometry(QtCore.QRect(0, 0, 63, 66))
        self.graphicsView_25.setStyleSheet("background:url(:/img/resources/weather/snowy.png);\n"
"border:transparent")
        self.graphicsView_25.setObjectName("graphicsView_25")
        self.stackedWeather.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.graphicsView_26 = QtWidgets.QGraphicsView(self.page_8)
        self.graphicsView_26.setGeometry(QtCore.QRect(0, 5, 63, 61))
        self.graphicsView_26.setStyleSheet("background:url(:/img/resources/weather/thunder.png);\n"
"border:transparent")
        self.graphicsView_26.setObjectName("graphicsView_26")
        self.stackedWeather.addWidget(self.page_8)
        self.weather = QtWidgets.QLabel(self.frame_5)
        self.weather.setGeometry(QtCore.QRect(110, 70, 51, 41))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(14)
        self.weather.setFont(font)
        self.weather.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.weather.setAlignment(QtCore.Qt.AlignCenter)
        self.weather.setObjectName("weather")
        self.weatherVal_2 = QtWidgets.QLabel(self.frame_5)
        self.weatherVal_2.setGeometry(QtCore.QRect(150, 40, 21, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        self.weatherVal_2.setFont(font)
        self.weatherVal_2.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.weatherVal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherVal_2.setObjectName("weatherVal_2")
        self.frame_6 = QtWidgets.QFrame(self.page_15)
        self.frame_6.setGeometry(QtCore.QRect(0, 106, 181, 125))
        self.frame_6.setStyleSheet("background:rgba(5,5,15,100);\n"
"border-radius : 5px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.dust = QtWidgets.QLabel(self.frame_6)
        self.dust.setGeometry(QtCore.QRect(110, 70, 51, 41))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(14)
        self.dust.setFont(font)
        self.dust.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.dust.setAlignment(QtCore.Qt.AlignCenter)
        self.dust.setObjectName("dust")
        self.stackedDust = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedDust.setGeometry(QtCore.QRect(15, 40, 71, 71))
        self.stackedDust.setStyleSheet("background:transparent;")
        self.stackedDust.setObjectName("stackedDust")
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setObjectName("page_20")
        self.graphicsView_18 = QtWidgets.QGraphicsView(self.page_20)
        self.graphicsView_18.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.graphicsView_18.setStyleSheet("background:url(:/img/resources/good.png);\n"
"border:transparent")
        self.graphicsView_18.setObjectName("graphicsView_18")
        self.stackedDust.addWidget(self.page_20)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.graphicsView_19 = QtWidgets.QGraphicsView(self.page_21)
        self.graphicsView_19.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.graphicsView_19.setStyleSheet("background:url(:/img/resources/normal.png);\n"
"border:transparent")
        self.graphicsView_19.setObjectName("graphicsView_19")
        self.stackedDust.addWidget(self.page_21)
        self.page_22 = QtWidgets.QWidget()
        self.page_22.setObjectName("page_22")
        self.graphicsView_20 = QtWidgets.QGraphicsView(self.page_22)
        self.graphicsView_20.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.graphicsView_20.setStyleSheet("background:url(:/img/resources/bad.png);\n"
"border:transparent")
        self.graphicsView_20.setObjectName("graphicsView_20")
        self.stackedDust.addWidget(self.page_22)
        self.page_23 = QtWidgets.QWidget()
        self.page_23.setObjectName("page_23")
        self.graphicsView_21 = QtWidgets.QGraphicsView(self.page_23)
        self.graphicsView_21.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.graphicsView_21.setStyleSheet("background:url(:/img/resources/worst.png);\n"
"border:transparent")
        self.graphicsView_21.setObjectName("graphicsView_21")
        self.stackedDust.addWidget(self.page_23)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, 3, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.label_21.setObjectName("label_21")
        self.dustVal = QtWidgets.QLabel(self.frame_6)
        self.dustVal.setGeometry(QtCore.QRect(95, 40, 41, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(15)
        self.dustVal.setFont(font)
        self.dustVal.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.dustVal.setAlignment(QtCore.Qt.AlignCenter)
        self.dustVal.setObjectName("dustVal")
        self.weatherVal_3 = QtWidgets.QLabel(self.frame_6)
        self.weatherVal_3.setGeometry(QtCore.QRect(130, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        self.weatherVal_3.setFont(font)
        self.weatherVal_3.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.weatherVal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherVal_3.setObjectName("weatherVal_3")
        self.time = QtWidgets.QLabel(self.page_15)
        self.time.setGeometry(QtCore.QRect(60, 45, 251, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setStyleSheet("background: transparent;\n"
"color:white\n"
"")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.date = QtWidgets.QLabel(self.page_15)
        self.date.setGeometry(QtCore.QRect(90, 15, 191, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.date.setFont(font)
        self.date.setStyleSheet("background: transparent;\n"
"color:white\n"
"")
        self.date.setObjectName("date")
        self.label_9 = QtWidgets.QLabel(self.page_15)
        self.label_9.setGeometry(QtCore.QRect(220, 53, 21, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(38)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgba(5,5,15,130);\n"
"background:transparent")
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.page_15)
        self.label_3.setGeometry(QtCore.QRect(132, 53, 16, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(38)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(5,5,15,130);\n"
"background:transparent")
        self.label_3.setObjectName("label_3")
        self.stackedPage.addWidget(self.page_15)
        self.page_24 = QtWidgets.QWidget()
        self.page_24.setObjectName("page_24")
        self.frame_7 = QtWidgets.QFrame(self.page_24)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 371, 231))
        self.frame_7.setStyleSheet("background:rgba(5,5,15,100);\n"
"border-radius : 5px")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_25 = QtWidgets.QLabel(self.frame_7)
        self.label_25.setGeometry(QtCore.QRect(10, 3, 101, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:white;\n"
"background:transparent\n"
"\n"
"")
        self.label_25.setObjectName("label_25")
        self.add = QtWidgets.QPushButton(self.frame_7)
        self.add.setGeometry(QtCore.QRect(310, 165, 23, 23))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.add.setFont(font)
        self.add.setStyleSheet("border:1px solid rgba(250,250,250,245);\n"
"border-radius:6px;\n"
"background:transparent;\n"
"color:rgba(250,250,250,245);")
        self.add.setObjectName("add")
        self.table = QtWidgets.QTableWidget(self.frame_7)
        self.table.setGeometry(QtCore.QRect(10, 35, 351, 123))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(12)
        self.table.setFont(font)
        self.table.setStyleSheet("QTableWidget\n"
"{\n"
"color:white;\n"
"border:1px solid white;\n"
"border-radius:2px;\n"
"background:transparent;\n"
"selection-background-color:white;\n"
"selection-color:black;\n"
"gridline-color:white;\n"
"}\n"
"QTableWidget QHeaderView::section{\n"
"background:white;\n"
"color:black;\n"
"}\n"
"QScrollBar:vertical{\n"
"background:transparent;\n"
"width: 10px;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background-color: white;}\n"
"QScrollBar::handle:vertical {\n"
"border-radius:5px;\n"
"background: white;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: transparent;\n"
"}\n"
"\n"
"")
        self.table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table.setMidLineWidth(0)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setAlternatingRowColors(False)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setShowGrid(True)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(False)
        self.table.setRowCount(1)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(11)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(11)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        item.setFont(font)
        self.table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        item.setFont(font)
        self.table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 2, item)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(35)
        self.table.horizontalHeader().setHighlightSections(False)
        self.table.horizontalHeader().setMinimumSectionSize(35)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setDefaultSectionSize(25)
        self.table.verticalHeader().setHighlightSections(False)
        self.table.verticalHeader().setMinimumSectionSize(25)
        self.sub = QtWidgets.QPushButton(self.frame_7)
        self.sub.setGeometry(QtCore.QRect(340, 165, 23, 23))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.sub.setFont(font)
        self.sub.setStyleSheet("border:1px solid rgba(250,250,250,245);\n"
"border-radius:6px;\n"
"background:transparent;\n"
"color:rgba(250,250,250,245);")
        self.sub.setObjectName("sub")
        self.reservePage = QtWidgets.QStackedWidget(self.frame_7)
        self.reservePage.setGeometry(QtCore.QRect(0, 160, 371, 71))
        self.reservePage.setStyleSheet("background:transparent\n"
"")
        self.reservePage.setObjectName("reservePage")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.brdcstEdit = QtWidgets.QLineEdit(self.page_4)
        self.brdcstEdit.setGeometry(QtCore.QRect(10, 37, 321, 25))
        self.brdcstEdit.setStyleSheet("background:rgba(255,255,255,245)\n"
"")
        self.brdcstEdit.setText("")
        self.brdcstEdit.setObjectName("brdcstEdit")
        self.brdcstTime = QtWidgets.QTimeEdit(self.page_4)
        self.brdcstTime.setGeometry(QtCore.QRect(105, 0, 111, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(12)
        self.brdcstTime.setFont(font)
        self.brdcstTime.setStyleSheet("QTimeEdit{background:transparent;\n"
"color:white;\n"
"selection-background-color: transparent;\n"
"selection-color:white}\n"
"QTimeEidt::down-arrow{\n"
"width:35px\n"
"}\n"
"")
        self.brdcstTime.setAlignment(QtCore.Qt.AlignCenter)
        self.brdcstTime.setCurrentSection(QtWidgets.QDateTimeEdit.AmPmSection)
        self.brdcstTime.setObjectName("brdcstTime")
        self.every = QtWidgets.QCheckBox(self.page_4)
        self.every.setGeometry(QtCore.QRect(10, 7, 51, 16))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(12)
        self.every.setFont(font)
        self.every.setStyleSheet("QCheckBox{background:transparent;\n"
"color:white}")
        self.every.setObjectName("every")
        self.enter = QtWidgets.QPushButton(self.page_4)
        self.enter.setGeometry(QtCore.QRect(340, 38, 23, 23))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.enter.setFont(font)
        self.enter.setStyleSheet("border:1px solid rgba(250,250,250,245);\n"
"border-radius:6px;\n"
"background:transparent;\n"
"color:rgba(250,250,250,245);")
        self.enter.setObjectName("enter")
        self.day = QtWidgets.QComboBox(self.page_4)
        self.day.setGeometry(QtCore.QRect(65, 5, 35, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 117, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 117, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 117, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.day.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(12)
        self.day.setFont(font)
        self.day.setStyleSheet("QComboBox{color:white;\n"
"background: transparent;\n"
"}QComboBox::drop-down{\n"
"background: transparent;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"color:white;\n"
"background-color:rgba(5,5,15,100);\n"
"selection-background-color:white;\n"
"selection-color:black}\n"
"")
        self.day.setFrame(False)
        self.day.setObjectName("day")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.day.addItem("")
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setGeometry(QtCore.QRect(87, 7, 16, 16))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white\n"
"")
        self.label.setObjectName("label")
        self.label.raise_()
        self.brdcstEdit.raise_()
        self.brdcstTime.raise_()
        self.every.raise_()
        self.enter.raise_()
        self.day.raise_()
        self.reservePage.addWidget(self.page_4)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.reservePage.addWidget(self.page_9)
        self.label_25.raise_()
        self.table.raise_()
        self.reservePage.raise_()
        self.add.raise_()
        self.sub.raise_()
        self.stackedPage.addWidget(self.page_24)
        self.buttons = QtWidgets.QStackedWidget(self.frame)
        self.buttons.setGeometry(QtCore.QRect(460, 250, 31, 41))
        self.buttons.setStyleSheet("background:transparent\n"
"")
        self.buttons.setObjectName("buttons")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.brdcstButton = QtWidgets.QPushButton(self.page)
        self.brdcstButton.setGeometry(QtCore.QRect(0, 10, 24, 24))
        self.brdcstButton.setStyleSheet("background:url(:/img/resources/microphone.png);\n"
"border:transparent")
        self.brdcstButton.setText("")
        self.brdcstButton.setObjectName("brdcstButton")
        self.buttons.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.homeButton = QtWidgets.QPushButton(self.page_2)
        self.homeButton.setGeometry(QtCore.QRect(0, 10, 24, 24))
        self.homeButton.setStyleSheet("background:url(:/img/resources/home-button.png);\n"
"border:transparent")
        self.homeButton.setText("")
        self.homeButton.setObjectName("homeButton")
        self.buttons.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedPage.setCurrentIndex(0)
        self.stackedWeather.setCurrentIndex(0)
        self.stackedDust.setCurrentIndex(1)
        self.reservePage.setCurrentIndex(0)
        self.buttons.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weatherVal.setText(_translate("MainWindow", "00.0"))
        self.label_18.setText(_translate("MainWindow", "Weather"))
        self.weather.setText(_translate("MainWindow", "맑음"))
        self.weatherVal_2.setText(_translate("MainWindow", "°C"))
        self.dust.setText(_translate("MainWindow", "매우\n"
"나쁨"))
        self.label_21.setText(_translate("MainWindow", "Fine Dust"))
        self.dustVal.setText(_translate("MainWindow", "000"))
        self.weatherVal_3.setText(_translate("MainWindow", "㎍/m3"))
        self.time.setText(_translate("MainWindow", "12  00  00"))
        self.date.setText(_translate("MainWindow", "2019년 12월 31일"))
        self.label_9.setText(_translate("MainWindow", ":"))
        self.label_3.setText(_translate("MainWindow", ":"))
        self.label_25.setText(_translate("MainWindow", "Broadcast"))
        self.add.setText(_translate("MainWindow", "+"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "상태"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "시각"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "내용"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 0)
        item.setText(_translate("MainWindow", "on"))
        item = self.table.item(0, 1)
        item.setText(_translate("MainWindow", "6:30"))
        item = self.table.item(0, 2)
        item.setText(_translate("MainWindow", "a"))
        self.table.setSortingEnabled(__sortingEnabled)
        self.sub.setText(_translate("MainWindow", "-"))
        self.every.setText(_translate("MainWindow", "매주"))
        self.enter.setText(_translate("MainWindow", "↵"))
        self.day.setItemText(0, _translate("MainWindow", "월"))
        self.day.setItemText(1, _translate("MainWindow", "화"))
        self.day.setItemText(2, _translate("MainWindow", "수"))
        self.day.setItemText(3, _translate("MainWindow", "목"))
        self.day.setItemText(4, _translate("MainWindow", "금"))
        self.day.setItemText(5, _translate("MainWindow", "토"))
        self.day.setItemText(6, _translate("MainWindow", "일"))
        self.label.setText(_translate("MainWindow", "▼ "))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

